In [1]:
import numpy as np

1. Create a null vector of size 10 but the fifth value which is 1

In [2]:
null_vector=np.zeros(10)
null_vector[5]=1
null_vector

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

2. Create a vector with values ranging from 10 to 49.

In [3]:
vector=np.arange(10,49)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

3. Create a 3x3 matrix with values ranging from 0 to 8

In [4]:
matrix=np.arange(0,9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [5]:
a=np.array([1,2,0,0,4,0])
np.nonzero(a)


(array([0, 1, 4], dtype=int64),)

5. Create a 10x10 array with random values and find the minimum and maximum values.

In [6]:
a=np.random.random([10,10])
print("The array is :", a)
print("\t")
print("The minimum values is :", np.min(a))
print("\t")
print("The minimum values is :", np.max(a))

The array is : [[0.5760555  0.56415503 0.76035667 0.25372516 0.63669865 0.62316051
  0.9403555  0.09018726 0.90914914 0.32841401]
 [0.95562422 0.00876284 0.77726907 0.38827084 0.99758079 0.45295798
  0.67820528 0.37518201 0.89755669 0.22420527]
 [0.14817669 0.88934332 0.51585851 0.63511816 0.44355848 0.62819156
  0.18067246 0.02661702 0.3547635  0.17825911]
 [0.17501751 0.46502391 0.71656346 0.31462625 0.00231303 0.96477197
  0.40773464 0.27028264 0.25127682 0.19837937]
 [0.83295303 0.57362114 0.4956406  0.02089263 0.72620478 0.79265416
  0.45991831 0.99030047 0.2289051  0.33696382]
 [0.3319934  0.40521626 0.72104795 0.4692711  0.69648906 0.55039568
  0.98915434 0.49275092 0.8823517  0.27622454]
 [0.44631934 0.22646504 0.48809779 0.61833964 0.18609478 0.23587136
  0.88773621 0.85284839 0.915295   0.03129125]
 [0.37633014 0.22981712 0.56449612 0.42987618 0.26533439 0.46139392
  0.01097658 0.83909021 0.30378749 0.03837303]
 [0.90954317 0.70446254 0.39918502 0.15878395 0.33050943 0.146035

6. Create a random vector of size 30 and find the mean value.

In [7]:
v=np.random.random(30)
print("The random Vector is : ", v)
print("\t")
print("The mean values is :",np.mean(v))

The random Vector is :  [0.25892721 0.3864405  0.51037719 0.71802921 0.31684707 0.51335426
 0.87437606 0.0511041  0.22565438 0.31685423 0.17285205 0.05742234
 0.60169065 0.59159456 0.55877435 0.43350758 0.96208609 0.52316769
 0.04503984 0.31851054 0.96361833 0.83800763 0.66249157 0.75847924
 0.40127844 0.88628474 0.2775188  0.6065536  0.09505981 0.40016166]
	
The mean values is : 0.4775354572493536
